CREATE TABLE new_features (
    id BIGSERIAL PRIMARY KEY,
    feature_name VARCHAR(255) NOT NULL,
    feature_description TEXT,
    status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);