# Generated by Django 5.2.4 on 2025-08-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementdraft',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirementdraft',
            name='generated_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
