# Generated by Django 5.2.4 on 2025-08-08 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_requirementdraft_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputdocument',
            name='doc_type',
            field=models.CharField(choices=[('기능명세서', '기능명세서'), ('업무분단표', '업무분단표'), ('로드맥', '로드맥'), ('간트차트', '간트차트')], max_length=20),
        ),
        migrations.CreateModel(
            name='GanttChart',
            fields=[
                ('GanttChart', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('total_weeks', models.PositiveIntegerField()),
                ('parts', models.JSONField(default=list)),
                ('generated_by', models.CharField(default='gemini_3', max_length=20)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_charts', to='auto_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='GanttTask',
            fields=[
                ('GanttTask', models.AutoField(primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=255)),
                ('start_week', models.PositiveIntegerField(default=1)),
                ('duration_weeks', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gantt_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auto_app.ganttchart')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto_app.requirement')),
            ],
            options={
                'ordering': ['part', 'order', 'GanttTask'],
            },
        ),
    ]
